[features]
seeds = true
skip-lint = false
[programs.devnet]
mint = "Hxr6EuH39zDmgPDcWTk2LpqA2ZZm6Ynhpd33nAR7v83P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
